### PR TITLE
Adds integration test

### PR DESCRIPTION
**Pull request by crystalhsieh**
I made a bash script to do basic integration testing -- it runs the server with a test_config and checks that the HTTP server returns the proper status code.

### CODE REVIEW

**Review by ryanvoong — COMMENTED** [review]
delete binaries. also add newline to end of server_integration_test.sh?

**Review by jasonsliu — APPROVED** [review]
Remove libgtest.a and the server_test binary please!

**Comment by crystalhsieh** [comment]
Removed binaries and added a new line. I also added the integration test to travis.

**Comment by ryanvoong** [comment]
looks good. merge!!!

**Pull request merged**
